apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-sofrano
  namespace: macro
spec:
  schedule: "50 21 * * *" # 6:50 AM UTC+9
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: selenium/standalone-chrome
            name: macro-sofrano
            command: ["bin/sh"]
            args:
              - "-c"
              - |
                sleep $((RANDOM % 90))
                set -e  
                apt-get update && apt-get install -y python3 python3-pip 
                pip3 install selenium webdriver-manager opencv-python pytesseract --break-system-package 
                apt-get install python3-pil tesseract-ocr libtesseract-dev tesseract-ocr-eng tesseract-ocr-script-latn -y 
                python3 /app/macro-sofrano.py 
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: macro-script-volume
                mountPath: /app/macro-sofrano.py
                subPath: macro-sofrano.py
            resources: {}
          volumes:
            - name: macro-script-volume
              configMap:
                name: cm-sofrano
          dnsPolicy: ClusterFirst
          restartPolicy: Never
